/**
 * @author StevenC
 */

package edu.CSUSM.testTaker.Backend;

/**
 * An interface for all objects that can be stored in LibraryController.
 * Operations that can be done on an object in the library regardless of what it is belong here.
 * @author StevenC
 */
public interface Registerable {
	
	/**
	 * This function has not been specified and the previous implementation in TaskObject didn't do anything.
	 */
	default public void getObjects(){};
	
	/**
	 * Set this object to be stored in a new location of the Library by resetting it's unique ID.
	 */
	abstract public void turnIntoDuplicate();
	
	/**
	 * Get the UUID String used as the Primary Key to register this object.
	 * @return A String generated by the toString of a java.util.UUID object
	 */
	abstract public String getID();
	
	/**
	 * Give a reasonable name or title String for this object.
	 * @return a String naming this object
	 */
	abstract public String getName();
	
	/**
	 * Give String representing the type of this object
	 * @return a String of the class of this object under edu.CSUSM.testTaker.Backend
	 */
	abstract public String getTypeName();
}
